name: Test

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install pkg-config cmake clang build-essential luarocks -y

    - name: Prepare macOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update || true
        brew install pkg-config luarocks || true

    - name: Prepare windows
      if: contains(matrix.os, 'windows')
      run: |
        wget "http://luarocks.github.io/luarocks/releases/luarocks-3.11.1-windows-32.zip" -outfile rocks.zip
        unzip rocks.zip

    - name: Install lua deps (windows)
      if: contains(matrix.os, 'windows')
      run: |
          luarocks-3.11.1-windows-32/luarocks.exe install --only-deps luaworlds-1.0-0.rockspec 

    - name: Install lua deps (nix)
      if: contains(matrix.os, 'macOS') || contains(matrix.os, 'ubuntu')
      run: |
          sudo luarocks install --only-deps luaworlds-1.0-0.rockspec 

    - name: Run tests
      run: |
        lua ./spec/*.lua

